sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
services:
  - docker
before_install:
  - docker build -t dhvlptl/testimage -f Dockerfile.dev .
script:
  - docker run -e CI=true dhvlptl/testimage npm test